# Generated by Django 3.2.6 on 2021-09-18 14:56

import adamInsrnceMngmnt.myStorage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_surveyor', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='profile_images')),
                ('bas64Image', models.TextField(blank=True, null=True)),
                ('imageType', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('socialImageUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement_number', models.CharField(blank=True, max_length=100, null=True)),
                ('endorsement_pdf', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='endorsments')),
                ('endorsement_issue_date', models.DateField()),
                ('previous_premium', models.IntegerField(blank=True, null=True)),
                ('new_premium', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('endorsement_added_to_system_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-endorsement_issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_issue_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_expiry_date', models.DateField(blank=True, null=True)),
                ('policy_pdf', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='policies')),
                ('premium', models.IntegerField(default=0)),
                ('policy_added_to_system_date', models.DateTimeField(auto_now_add=True)),
                ('branch_ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('main_acc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('end_claim_number', models.CharField(blank=True, max_length=100, null=True)),
                ('outstanding', models.IntegerField(default=0)),
                ('percentage_premium_paid', models.IntegerField()),
                ('l_c_number', models.CharField(blank=True, max_length=100, null=True)),
                ('b_l_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentPolicies', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insrnceDataApp.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPolicies', to=settings.AUTH_USER_MODEL)),
                ('latest_financial_endorsement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='if_latest_then_policy', to='insrnceDataApp.endorsement')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-policy_issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_pdf_file', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='temp_policies')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='receipts')),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('premium_paid', models.IntegerField()),
                ('edit_premium_paid', models.IntegerField(default=0)),
                ('receipt_added_to_system_date', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsRecieved', to='insrnceDataApp.policy')),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.AddField(
            model_name='endorsement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='insrnceDataApp.policy'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='previous_financial_endorsement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_financial_endorsement', to='insrnceDataApp.endorsement'),
        ),
    ]
