# Generated by Django 3.2.6 on 2021-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insrnceDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='endorsement_issue_date',
            field=models.DateTimeField(),
        ),
    ]
