# Generated by Django 3.2.6 on 2021-10-24 07:46

import adamInsrnceMngmnt.myStorage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insrnceDataApp', '0002_alter_endorsement_endorsement_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_loss', models.DateField()),
                ('claim_number', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_form', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='claim_forms')),
                ('claim_estimate', models.IntegerField(blank=True, null=True)),
                ('claim_bill', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='claim_bills')),
                ('bill_cost', models.IntegerField(blank=True, null=True)),
                ('police_report', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='police_reports')),
                ('departmental_inquiry_report', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='inquiry_reports')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('vehicle_registration_copy', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='registration')),
                ('driving_license', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='driving_license')),
                ('cnic_copy', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='cnic_copies')),
                ('driver_statement', models.TextField(blank=True, null=True)),
                ('fire_brigade_report', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='fire_reports')),
                ('bill_of_ladding', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='laddings')),
                ('commercial_invoice', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='commercial_invoices')),
                ('misc_document_1', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='misc_docs')),
                ('misc_document_2', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='misc_docs')),
                ('misc_document_3', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='misc_docs')),
                ('misc_document_4', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='misc_docs')),
                ('misc_document_5', models.FileField(blank=True, null=True, storage=adamInsrnceMngmnt.myStorage.OverwriteStorage(), upload_to='misc_docs')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insrnceDataApp.policy')),
            ],
            options={
                'ordering': ['-date_of_loss'],
            },
        ),
    ]
