# Generated by Django 3.2.6 on 2021-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insrnceDataApp', '0003_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '     2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-date_of_loss'], 'verbose_name_plural': ' 6. Claims'},
        ),
        migrations.AlterModelOptions(
            name='endorsement',
            options={'ordering': ['-endorsement_issue_date'], 'verbose_name_plural': '   4. Endorsements'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-policy_issue_date'], 'verbose_name_plural': '    3. Policies'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-receipt_date'], 'verbose_name_plural': '  5. Receipts'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '      1. Agents, surveyers and clients'},
        ),
        migrations.AddField(
            model_name='policy',
            name='gross_premium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policy',
            name='percentage_on_gross_premium_for_comission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='policy',
            name='personal_comission',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=16),
        ),
    ]
